export const TASK_ACTIONS = {
  CREATED: 'CREATED',
  UPDATED: 'UPDATED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  ASSIGNED: 'ASSIGNED',
  REASSIGNED: 'REASSIGNED',
  COMMENT_ADDED: 'COMMENT_ADDED',
  SOFT_DELETED: 'SOFT_DELETED',
} as const;

export type TaskAction = (typeof TASK_ACTIONS)[keyof typeof TASK_ACTIONS];
